### ISSUE TITLE
Warning in PHPUnit 8.0

### ISSUE THREAD

**Issue by kenwilliams5** [alphametric/mail-assertions#1]
PHPUnit 8.0 issues a deprecation warning when using assertEmailBodyContains. That function should have the *assertContains* changed to *assertStringContainsString* as shown:

```
protected function assertEmailBodyContains($payload, Message $message = null)
	{
		// Execute test
		$this -> assertStringContainsString(
			$payload, $this -> getEmail($message) -> getBody(), "The last (or given) email did not contain the provided body."
		);

		// Return instance
		return $this;
	}
```

**Comment by alphametric** [comment]
Thanks for pointing this out and sorry for the delay. Will sort this tomorrow...

**Comment by alphametric** [comment]
Okay, version 2.0 adds support for PHPUnit 8.
